[world.overview]
summary = "Vana'diel rebuilds after the Crystal War. The great nations maintain an uneasy alliance while Beastmen and ancient threats stir on the frontiers. Elemental crystals still power magic and technology, but rumors speak of a deeper calamity waiting to be awakened."

[[world.history]]
name = "Age of Dawn"
summary = "Mythic era when the gods shaped the land and placed the Mothercrystals."

[[world.history]]
name = "Rise of the Zilart"
summary = "An advanced race built sky cities and sought to reach paradise, leaving ruins across the world."

[[world.history]]
name = "Great Rupture"
summary = "A calamity shattered the Zilart's plans, scattering their civilization and sealing away forbidden magic."

[[world.history]]
name = "Crystal War"
summary = "Recent conflict where the allied nations fought the Shadow Lord and his Beastmen armies."

[[world.history]]
name = "Current Era"
summary = "Two decades after the war, exploration of ruins and political intrigue accelerate as old wounds reopen."

[[regions]]
name = "Ronfaure"
biome = "Forested valleys and rolling hills"
locations = ["San d'Oria", "Briarwood Village", "Ghelsba Outpost", "Orcish ruins"]
factions = ["Kingdom of San d'Oria", "Orc Tribes"]

[[regions]]
name = "Gustaberg"
biome = "Rugged mountains and mining fields"
locations = ["Bastok", "South Gustaberg Outpost", "Palborough Mines", "Crumbling Keep"]
factions = ["Republic of Bastok", "Quadav clans"]

[[regions]]
name = "Sarutabaruta"
biome = "Warm savanna and jungles"
locations = ["Windurst", "Starfall Village", "Castle Oztroja", "Ancient research domes"]
factions = ["Federation of Windurst", "Yagudo theocracy"]

[[regions]]
name = "La Theine Highlands"
biome = "Highland plains and windswept plateaus"
locations = ["Frontier Outpost", "La Theine Gorge", "Hidden caverns"]
factions = ["Adventurers' League", "wandering Beastmen"]

[[factions]]
name = "Kingdom of San d'Oria"
goal = "Protect Elvaan lands and uphold chivalric code"
alignment = "Lawful Neutral"

[[factions]]
name = "Republic of Bastok"
goal = "Expand mining operations and technological influence"
alignment = "Neutral"

[[factions]]
name = "Federation of Windurst"
goal = "Advance magical knowledge while safeguarding the forests"
alignment = "Neutral Good"

[[factions]]
name = "Beastmen Tribes"
goal = "Regain lost territories and challenge the nations"
alignment = "Chaotic Evil"

[[factions]]
name = "Arcane Circle"
goal = "Study relics and unseal ancient magic"
alignment = "Chaotic Neutral"

[[races]]
name = "Humes"
traits = "Adaptable and ambitious"
culture = "Merchant guilds and republican ideals"
origin = "Spread across Bastok and smaller towns"

[[races]]
name = "Elvaan"
traits = "Tall warriors with strong faith"
culture = "Knightly orders and strict traditions"
origin = "Forests of Ronfaure"

[[races]]
name = "Tarutaru"
traits = "Small, magically gifted"
culture = "Scholarly federations and playful customs"
origin = "Sarutabaruta"

[[races]]
name = "Mithra"
traits = "Feline agility and sharp senses"
culture = "Tribal hunters and scouts"
origin = "Coastal and jungle villages"

[[races]]
name = "Galka"
traits = "Massive strength and a stoic outlook"
culture = "Nomadic laborers with a reincarnation myth"
origin = "Desert wastes near Bastok"

[[magic]]
schools = ["Elemental", "Healing", "Shadow", "Geomancy", "Summoning"]
limits = "Spells draw energy from crystals; overuse can corrupt the caster"
artifacts = ["ancient Zilart focus stones", "crystal-bound grimoires"]

[[hooks]]
summary = "Goblins raid Briarwood Village seeking a lost Zilart artifact; players uncover the first clue to a wider conspiracy."

[[hooks]]
summary = "A frontier outpost in La Theine asks for aid against mysterious undead rising from hidden caverns."

[[hooks]]
summary = "Scholars of the Arcane Circle hire adventurers to explore a crumbling keep in Gustaberg for shards of forbidden magic."

[[hooks]]
summary = "Rumors spread of a forgotten god sealed beneath Castle Oztroja; the Yagudo plan a ritual to awaken it."



# Additional Lore Sections

[[characters]]
name = "Alynna"
role = "Young Elvaan knight"
origin = "Ronfaure"
description = "Driven to prove herself after the Crystal War, she mentors the player in San d'Oria."

[[characters]]
name = "Garrick"
role = "Hume engineer"
origin = "Bastok"
description = "Obsessed with rediscovering lost Zilart machinery to strengthen his nation."

[[characters]]
name = "Shalira"
role = "Mithra scout"
origin = "Windurst"
description = "Explores ruins for clues about her tribe's past and guides players through the frontier."

[[characters]]
name = "Eldran"
role = "Mysterious wanderer"
origin = "Unknown"
description = "A figure tied to the sealed god, appearing in visions during early quests."

[mythology]
creation_story = "Altana wept five tears that became the Mothercrystals, giving life to Vana'diel."
gods = ["Altana the Dawn Goddess", "Promathia the Twilight God"]
ancient_calamity = "The Zilart tried to open the Gate of the Gods and unleashed the Great Rupture."
elemental_crystals = ["Fire", "Ice", "Wind", "Earth", "Lightning", "Water", "Light", "Dark"]

[[race_lore]]
race = "Humes"
history = "Once scattered nomads, they united under Bastok and now pursue industry and commerce."
beliefs = "Value ingenuity and personal freedom."

[[race_lore]]
race = "Elvaan"
history = "Descended from holy guardians of the northern forests."
beliefs = "Hold chivalry and faith above all else."

[[race_lore]]
race = "Tarutaru"
history = "Ancient magic scholars who built Windurst's academies."
beliefs = "Knowledge is the highest virtue, though mischief is common."

[[race_lore]]
race = "Mithra"
history = "Nomadic hunters that now share Windurst while keeping tribal traditions."
beliefs = "Respect for nature and fierce loyalty to kin."

[[race_lore]]
race = "Galka"
history = "A warrior people with a cycle of reincarnation, wandering the deserts."
beliefs = "Strength and resilience guide their path."

[[nation_lore]]
name = "Kingdom of San d'Oria"
capital = "San d'Oria"
government = "Theocratic monarchy led by the royal family and cathedral."
conflicts = "Struggles against Orc tribes and internal disputes over succession."

[[nation_lore]]
name = "Republic of Bastok"
capital = "Bastok"
government = "Industrial republic with a president and council of miners."
conflicts = "Clashes with the Quadav and tensions with Galka laborers."

[[nation_lore]]
name = "Federation of Windurst"
capital = "Windurst"
government = "Magocratic council headed by the Star Sibyl."
conflicts = "Beset by Yagudo zealots and arcane experiments gone awry."

[intro_quest]
start = "Briarwood Village"
summary = "Goblins raid the forest village seeking a crystal shard. Tracking them leads the player through La Theine to a crumbling keep, uncovering hints of an awakened deity."

