name: CI

on:
  pull_request:
    paths:
      - '**/*.rs'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash vanadiel_rpg/scripts/fetch_assets.sh
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo check --workspace --all-targets
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: '**/*.md'
