[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking"] }
bevy_ecs_tilemap = "0.16"
serde = { version = "1", features = ["derive"] }
ron = "0.8"
anyhow = "1"

[features]
default = []
